# Generated by Django 4.2.4 on 2023-08-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
